//! FFI bindings to Google's Longfellow ZK proving system.
//!
//! This crate provides raw C FFI bindings generated by bindgen,
//! plus safe Rust wrappers for the mdoc prover/verifier API.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

pub mod safe;
pub mod mdoc;

#[cfg(test)]
mod tests {
    use super::*;
    use std::ptr;

    #[test]
    fn bindings_exist() {
        // Verify struct sizes are non-zero (symbols linked correctly)
        assert!(std::mem::size_of::<RequestedAttribute>() > 0);
        assert!(std::mem::size_of::<ZkSpecStruct>() > 0);
    }

    /// Get a pointer to the first ZkSpec (1-attribute, latest version)
    unsafe fn get_spec() -> *const ZkSpecStruct {
        // kZkSpecs is extern — access via raw pointer arithmetic
        let base = kZkSpecs.as_ptr();
        assert!(!base.is_null());
        base
    }

    #[test]
    fn generate_circuit_works() {
        unsafe {
            let spec = get_spec();
            let mut circuit: *mut u8 = ptr::null_mut();
            let mut circuit_len: std::os::raw::c_ulong = 0;

            let ret = generate_circuit(spec, &mut circuit, &mut circuit_len);
            assert_eq!(ret, CircuitGenerationErrorCode_CIRCUIT_GENERATION_SUCCESS);
            assert!(circuit_len > 0);
            assert!(!circuit.is_null());

            libc::free(circuit as *mut libc::c_void);
        }
    }

    #[test]
    fn null_mdoc_returns_error() {
        unsafe {
            let spec = get_spec();
            let mut circuit: *mut u8 = ptr::null_mut();
            let mut circuit_len: std::os::raw::c_ulong = 0;
            generate_circuit(spec, &mut circuit, &mut circuit_len);

            let mut proof: *mut u8 = ptr::null_mut();
            let mut proof_len: std::os::raw::c_ulong = 0;

            let ret = run_mdoc_prover(
                circuit,
                circuit_len,
                ptr::null(),
                0, // null mdoc
                ptr::null(),
                ptr::null(), // null issuer key
                ptr::null(),
                0, // null transcript
                ptr::null(),
                0, // no attrs
                ptr::null(), // null time
                &mut proof,
                &mut proof_len,
                spec,
            );

            assert_ne!(ret, MdocProverErrorCode_MDOC_PROVER_SUCCESS);

            libc::free(circuit as *mut libc::c_void);
        }
    }

    #[test]
    fn full_prove_verify_round_trip() {
        // End-to-end: generate circuit, prove age_over_18, verify — all via FFI
        unsafe {
            let ret = longfellow_smoke_test();
            assert_eq!(ret, 0, "smoke test failed with code {ret}");
        }
    }

    #[test]
    fn verification_type_enum_values() {
        assert_eq!(VerificationType_VERIFY_EQ, 0);
        assert_eq!(VerificationType_VERIFY_LEQ, 1);
        assert_eq!(VerificationType_VERIFY_GEQ, 2);
        assert_eq!(VerificationType_VERIFY_NEQ, 3);
    }
}
