/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as UkraineRouteImport } from './routes/ukraine'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as PrintRouteImport } from './routes/print'
import { Route as LongfellowRouteImport } from './routes/longfellow'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as IndexRouteImport } from './routes/index'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const UkraineRoute = UkraineRouteImport.update({
  id: '/ukraine',
  path: '/ukraine',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const LongfellowRoute = LongfellowRouteImport.update({
  id: '/longfellow',
  path: '/longfellow',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contracts': typeof ContractsRoute
  '/demo': typeof DemoRoute
  '/learn': typeof LearnRoute
  '/longfellow': typeof LongfellowRoute
  '/print': typeof PrintRoute
  '/sandbox': typeof SandboxRoute
  '/ukraine': typeof UkraineRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contracts': typeof ContractsRoute
  '/demo': typeof DemoRoute
  '/learn': typeof LearnRoute
  '/longfellow': typeof LongfellowRoute
  '/print': typeof PrintRoute
  '/sandbox': typeof SandboxRoute
  '/ukraine': typeof UkraineRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contracts': typeof ContractsRoute
  '/demo': typeof DemoRoute
  '/learn': typeof LearnRoute
  '/longfellow': typeof LongfellowRoute
  '/print': typeof PrintRoute
  '/sandbox': typeof SandboxRoute
  '/ukraine': typeof UkraineRoute
  '/verify': typeof VerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contracts'
    | '/demo'
    | '/learn'
    | '/longfellow'
    | '/print'
    | '/sandbox'
    | '/ukraine'
    | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contracts'
    | '/demo'
    | '/learn'
    | '/longfellow'
    | '/print'
    | '/sandbox'
    | '/ukraine'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/contracts'
    | '/demo'
    | '/learn'
    | '/longfellow'
    | '/print'
    | '/sandbox'
    | '/ukraine'
    | '/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContractsRoute: typeof ContractsRoute
  DemoRoute: typeof DemoRoute
  LearnRoute: typeof LearnRoute
  LongfellowRoute: typeof LongfellowRoute
  PrintRoute: typeof PrintRoute
  SandboxRoute: typeof SandboxRoute
  UkraineRoute: typeof UkraineRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ukraine': {
      id: '/ukraine'
      path: '/ukraine'
      fullPath: '/ukraine'
      preLoaderRoute: typeof UkraineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/longfellow': {
      id: '/longfellow'
      path: '/longfellow'
      fullPath: '/longfellow'
      preLoaderRoute: typeof LongfellowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContractsRoute: ContractsRoute,
  DemoRoute: DemoRoute,
  LearnRoute: LearnRoute,
  LongfellowRoute: LongfellowRoute,
  PrintRoute: PrintRoute,
  SandboxRoute: SandboxRoute,
  UkraineRoute: UkraineRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
