//! CMS/X.509 parser — locates every byte range the circuit needs.
//!
//! Strategy: parse semantically with the `cms` / `x509-cert` crates, then
//! re-encode each sub-structure and locate it in the original DER via
//! byte search. Works because DER encoding is canonical for the fields
//! we care about.

use cms::content_info::ContentInfo;
use cms::signed_data::SignedData;
use const_oid::ObjectIdentifier;
use der::{Decode, Encode};
use x509_cert::Certificate;

use crate::{locator, P7sError, P7sOffsets};

/// OID 2.5.4.5 — X.520 serialNumber attribute.
const OID_SERIAL_NUMBER: ObjectIdentifier = ObjectIdentifier::new_unwrap("2.5.4.5");

/// 26-byte P-256 SPKI DER prefix — identical to the constant the
/// p7s circuit asserts on-wire at `cert_tbs[spki_offset..+26]`. Source
/// of truth is this host constant; the submodule's
/// `vendor/longfellow-zk/lib/circuits/p7s/p7s_zk.cc` carries the same
/// 26 bytes in `kSpkiDiaP256Prefix`. Any change requires updating both
/// sites.
///
/// The bytes encode the SPKI `AlgorithmIdentifier` SEQUENCE (OID
/// `id-ecPublicKey` + OID `prime256v1`) followed by the BIT STRING
/// header. These are universal across any P-256-issuing QTSP — the
/// synthetic TestAnchorA fixtures built by `gen_synthetic_fixtures`
/// use the same prefix by construction, matching the real DIIA
/// QTSP 2311 layout that was in place pre-#43a.
#[cfg_attr(feature = "test-bypass-host-anchors", allow(dead_code))]
const DIIA_P256_SPKI_PREFIX: [u8; 26] = [
    0x30, 0x59,                                     // SPKI SEQ hdr (l=89)
    0x30, 0x13,                                     // AlgId SEQ hdr (l=19)
    0x06, 0x07, 0x2a, 0x86, 0x48, 0xce, 0x3d,       // OID id-ecPublicKey
    0x02, 0x01,
    0x06, 0x08, 0x2a, 0x86, 0x48, 0xce, 0x3d,       // OID prime256v1 (P-256)
    0x03, 0x01, 0x07,
    0x03, 0x42, 0x00,                               // BIT STRING hdr (l=66)
];

/// 9-byte X.520 serialNumber attribute DER prefix. Identical to
/// `kSubjectSnAnchor` in the p7s circuit, asserted on-wire at
/// `cert_tbs[subject_sn_offset..subject_sn_offset+9]`. Attribute
/// SEQUENCE hdr (l=23 = 0x17) + OID 2.5.4.5 (id-at-serialNumber) +
/// PrintableString hdr (l=16 = 0x10). The 16-byte stable-ID value
/// follows. v1 (Task #34) fixes the lengths at 23/16 — valid for
/// DIIA TINUA-prefixed RNOKPP stable-IDs which are always 16 bytes
/// (`TINUA-` + 10 decimal digits). ETSI EN 319 412-1 §5.1.3 allows
/// variable stable-ID lengths; support for non-DIIA QTSPs with
/// different lengths is a Task #37 follow-up.
#[cfg_attr(feature = "test-bypass-host-anchors", allow(dead_code))]
const X520_SUBJECT_SN_ANCHOR: [u8; 9] = [
    0x30, 0x17,                       // Attribute SEQUENCE hdr (l=23)
    0x06, 0x03, 0x55, 0x04, 0x05,     // OID 2.5.4.5 (id-at-serialNumber)
    0x13, 0x10,                       // PrintableString hdr (l=16)
];

/// Fixed stable-ID value length in bytes. Matches the DIIA RNOKPP
/// format `TINUA-` (6 bytes) + 10 decimal digits = 16 bytes. Kept
/// in sync with the circuit-side `kStableIdLen` constant.
pub(crate) const STABLE_ID_LEN: usize = 16;

/// Trust-anchor probe table (Task #36 host-side mirror of the
/// submodule's `kTrustAnchors[]`). Each entry maps a unique,
/// hard-to-spoof marker from the signer cert's issuer DN to the
/// compile-time trust-anchor table index. Order must match the
/// submodule's `kTrustAnchors[]` so `trust_anchor_index = N` on
/// both sides selects the SAME anchor.
///
/// Post-Task-#43a Phase 2b ships with index 0 = TestAnchorA (synthetic
/// P-256 anchor whose signer cert was generated by
/// `gen_synthetic_fixtures`). It is identified by the synthetic QTSP
/// registration code `TQSA-00000000-01` embedded in the issuer DN's
/// serialNumber attribute. The earlier DIIA QTSP 2311 marker
/// (`UA-43395033-2311`) was removed as part of the PII-scrub when the
/// committed DIIA fixtures were replaced with synthetic equivalents.
/// Task #37 appends real-QTSP markers once non-PII fixtures land.
///
/// Using a byte-level substring match on the issuer DN's DER is
/// robust to DN attribute ordering (X.500 / X.509 RDNs are a SET
/// and issuers are free to permute them) because the reg-code
/// string itself is unique to the QTSP and stable across cert
/// re-issues within a given root.
const TRUST_ANCHOR_PROBES: &[(&[u8], u32, &str)] = &[
    (b"TQSA-00000000-01", 0, "TestAnchorA (synthetic, P-256)"),
];

/// 17-byte CMS messageDigest attribute DER prefix (RFC 5652). Identical
/// to `kSignedAttrsMdPrefix` in the p7s circuit, asserted on-wire at
/// `signed_attrs[md_offset..md_offset+17]`. Attribute SEQUENCE hdr
/// (l=47) + OID messageDigest + SET OF AttributeValue hdr (l=34) +
/// OCTET STRING hdr (l=32). The 32-byte SHA-256 digest value follows.
/// Any change requires updating both sites.
#[cfg_attr(feature = "test-bypass-host-anchors", allow(dead_code))]
const CMS_MESSAGE_DIGEST_ATTR_PREFIX: [u8; 17] = [
    0x30, 0x2f,                                     // Attribute SEQUENCE (l=47)
    0x06, 0x09, 0x2a, 0x86, 0x48, 0x86, 0xf7,       // OID messageDigest
    0x0d, 0x01, 0x09, 0x04,                         // (1.2.840.113549.1.9.4)
    0x31, 0x22,                                     // SET OF AttributeValue (l=34)
    0x04, 0x20,                                     // OCTET STRING hdr (l=32)
];

/// Parse the p7s and locate every byte range of interest.
pub(crate) fn locate_offsets(p7s: &[u8]) -> Result<P7sOffsets, P7sError> {
    // ── ContentInfo + SignedData ──────────────────────────────────────
    let ci = ContentInfo::from_der(p7s)
        .map_err(|e| P7sError::Cms(format!("ContentInfo: {e}")))?;
    let sd_bytes = ci
        .content
        .to_der()
        .map_err(|e| P7sError::Cms(format!("SignedData encode: {e}")))?;
    let sd = SignedData::from_der(&sd_bytes)
        .map_err(|e| P7sError::Cms(format!("SignedData: {e}")))?;

    // ── Signed content (JSON) ─────────────────────────────────────────
    let econtent = sd
        .encap_content_info
        .econtent
        .as_ref()
        .ok_or(P7sError::Cms("no eContent".into()))?;
    // econtent is an Any wrapping an OCTET STRING — get its inner bytes
    let econtent_der = econtent
        .to_der()
        .map_err(|e| P7sError::Cms(format!("eContent encode: {e}")))?;
    // Skip the outer Any tag+len and the OCTET STRING tag+len to get raw JSON
    let json_bytes = strip_any_octet_string(&econtent_der)?;
    let signed_content_start = find_subslice_unique(p7s, json_bytes)
        .ok_or(P7sError::OffsetNotFound("signed_content (JSON)"))?;
    let signed_content_len = json_bytes.len();

    // ── Signer certificate ────────────────────────────────────────────
    let cert_set = sd
        .certificates
        .as_ref()
        .ok_or(P7sError::NoCerts)?;
    // cms::signed_data::CertificateSet is a SetOfVec<CertificateChoices>
    // Take the first certificate-choice that is a plain Certificate.
    let signer_cert = first_x509_cert(cert_set)?;
    let cert_der = signer_cert
        .to_der()
        .map_err(|e| P7sError::Cms(format!("cert encode: {e}")))?;
    let cert_start = find_subslice_unique(p7s, &cert_der)
        .ok_or(P7sError::OffsetNotFound("cert"))?;
    let cert_len = cert_der.len();

    // TBSCertificate portion
    let tbs_der = signer_cert
        .tbs_certificate
        .to_der()
        .map_err(|e| P7sError::Cms(format!("tbs encode: {e}")))?;
    let cert_tbs_start = cert_start
        + find_subslice_unique(&cert_der, &tbs_der)
            .ok_or(P7sError::OffsetNotFound("tbs"))?;
    let cert_tbs_len = tbs_der.len();

    // Cert signature bytes (BIT STRING content — raw DER-encoded ECDSA SEQUENCE)
    let cert_sig_bitstring = signer_cert.signature.raw_bytes();
    let cert_sig_start = cert_start
        + find_subslice_unique(&cert_der, cert_sig_bitstring)
            .ok_or(P7sError::OffsetNotFound("cert signature"))?;
    let cert_sig_len = cert_sig_bitstring.len();

    // ── Subject serialNumber (stable ID) ──────────────────────────────
    let sn_value = signer_cert
        .tbs_certificate
        .subject
        .0
        .iter()
        .flat_map(|rdn| rdn.0.iter())
        .find(|atv| atv.oid == OID_SERIAL_NUMBER)
        .ok_or(P7sError::NoSerialNumber)?;
    // The value is an Any containing a PrintableString / UTF8String —
    // we want the inner bytes (not the DER tag+length).
    let sn_any_der = sn_value
        .value
        .to_der()
        .map_err(|e| P7sError::Der(format!("sn value: {e}")))?;
    let sn_inner = strip_tag_and_length(&sn_any_der)?;
    let subject_sn_start = cert_start
        + find_subslice_unique(&cert_der, sn_inner)
            .ok_or(P7sError::OffsetNotFound("subject serialNumber"))?;
    let subject_sn_len = sn_inner.len();

    // ── Subject DN start (invariant 7 dual-match range check anchor) ───
    // Locate the outer Subject DN SEQUENCE within the TBS. Anything
    // before it (in particular the Issuer DN, which also contains an
    // X.520 serialNumber attribute for the QTSP's reg code) must be
    // rejected as a stable-ID offset via the in-circuit range check
    // `subject_sn_offset > subject_dn_start_offset`.
    let subject_dn_der = signer_cert
        .tbs_certificate
        .subject
        .to_der()
        .map_err(|e| P7sError::Der(format!("subject DN encode: {e}")))?;
    let subject_dn_start_offset_in_tbs =
        find_subslice_unique(&tbs_der, &subject_dn_der)
            .ok_or(P7sError::OffsetNotFound("subject DN within TBS"))?;

    // ── Trust-anchor selection (Task #36) ─────────────────────────────
    // Probe the signer cert's issuer DN for a known QTSP marker and
    // emit the matching trust-anchor table index. The circuit's
    // compile-time `kTrustAnchors[]` and the host-side
    // `TRUST_ANCHOR_PROBES` are order-aligned by construction: both
    // use index 0 for DIIA, and future entries append symmetrically.
    let issuer_der = signer_cert
        .tbs_certificate
        .issuer
        .to_der()
        .map_err(|e| P7sError::Der(format!("issuer DN encode: {e}")))?;
    let trust_anchor_index = TRUST_ANCHOR_PROBES
        .iter()
        .find_map(|(marker, idx, _name)| {
            if contains_subslice(&issuer_der, marker) {
                Some(*idx)
            } else {
                None
            }
        })
        .ok_or_else(|| {
            P7sError::UnknownTrustAnchor(format!(
                "issuer DN does not match any of {} known QTSP markers",
                TRUST_ANCHOR_PROBES.len()
            ))
        })?;

    // Offset within cert_tbs of the 9-byte X.520 serialNumber attribute
    // prefix (SEQUENCE + OID + PrintableString hdr). Value bytes follow
    // at `subject_sn_offset_in_tbs + 9`. Host-witnessed — the subject
    // DN's length varies across DIIA holders; the circuit anchors the
    // 9-byte prefix on-wire via byte_eq.
    const SUBJECT_SN_ANCHOR_LEN: usize = 9;
    let subject_sn_offset_in_tbs = subject_sn_start
        .checked_sub(cert_tbs_start)
        .and_then(|p| p.checked_sub(SUBJECT_SN_ANCHOR_LEN))
        .ok_or(P7sError::OffsetNotFound(
            "subject serialNumber offset within cert_tbs",
        ))?;
    // v1 — enforce the DIIA-fixed 16-byte stable-ID length matching
    // the circuit's compile-time `kStableIdLen`. Non-DIIA QTSPs with
    // different RNOKPP-analog lengths are a Task #37 follow-up (when
    // the circuit gains variable-length support).
    if subject_sn_len != STABLE_ID_LEN {
        return Err(P7sError::Cms(format!(
            "subject serialNumber length {} != expected {} (v1 is DIIA-only; \
             non-DIIA QTSP support is deferred to Task #37)",
            subject_sn_len, STABLE_ID_LEN
        )));
    }
    // Host-side 9-byte anchor check — gated by the shared test-bypass
    // feature flag (same rationale as SPKI / messageDigest anchors:
    // bypass lets invariant_7 tests exercise the in-circuit anchor as
    // the sole enforcement layer).
    #[cfg(not(feature = "test-bypass-host-anchors"))]
    {
        let anchor_actual =
            &p7s[cert_tbs_start + subject_sn_offset_in_tbs..][..SUBJECT_SN_ANCHOR_LEN];
        if anchor_actual != X520_SUBJECT_SN_ANCHOR {
            return Err(P7sError::Cms(
                "X.520 serialNumber attribute DER prefix does not match \
                 (30 17 06 03 55 04 05 13 10 — id-at-serialNumber + \
                 PrintableString(16))".into(),
            ));
        }
    }

    // ── User signing pubkey (P-256 uncompressed point) ────────────────
    let spki_bitstring = signer_cert
        .tbs_certificate
        .subject_public_key_info
        .subject_public_key
        .raw_bytes();
    if spki_bitstring.len() != 65 || spki_bitstring[0] != 0x04 {
        return Err(P7sError::NotP256);
    }
    let user_signing_pk_start = cert_start
        + find_subslice_unique(&cert_der, spki_bitstring)
            .ok_or(P7sError::OffsetNotFound("user signing pk"))?;

    // SPKI offset WITHIN cert_tbs — the 26-byte DIIA P-256 SPKI DER
    // prefix sits at `cert_tbs[spki_offset..spki_offset + 26]`, and
    // the 65-byte SEC1 point (SEC1 0x04 at `spki_offset + 26`) sits
    // at `cert_tbs[spki_offset + 26..spki_offset + 91]`. Mirror of
    // the in-circuit anchor in vendor/longfellow-zk/lib/circuits/p7s/
    // p7s_zk.cc's `build_hash_circuit`. Host-side check gives a clean
    // P7sError on non-DIIA / non-P-256 certs instead of an opaque
    // circuit-level failure.
    const SPKI_PREFIX_LEN: usize = 26;
    let cert_tbs_spki_offset = user_signing_pk_start
        .checked_sub(cert_tbs_start)
        .and_then(|p| p.checked_sub(SPKI_PREFIX_LEN))
        .ok_or(P7sError::OffsetNotFound("SPKI offset within cert_tbs"))?;
    // Host-side SPKI anchor check — same gating rationale as the
    // messageDigest anchor below (bypass under the
    // `test-bypass-host-anchors` feature so invariant_2a test-11b can
    // exercise the in-circuit anchor as the sole enforcement layer).
    #[cfg(not(feature = "test-bypass-host-anchors"))]
    {
        let spki_prefix_actual =
            &p7s[cert_tbs_start + cert_tbs_spki_offset..][..SPKI_PREFIX_LEN];
        if spki_prefix_actual != DIIA_P256_SPKI_PREFIX {
            return Err(P7sError::Cms(
                "cert SPKI DER prefix does not match DIIA P-256 template".into(),
            ));
        }
    }

    // ── SignerInfo content signature ──────────────────────────────────
    let signer_info = sd
        .signer_infos
        .0
        .iter()
        .next()
        .ok_or(P7sError::Cms("no SignerInfo".into()))?;
    let content_sig_bytes = signer_info.signature.as_bytes();
    let content_sig_start = find_subslice_unique(p7s, content_sig_bytes)
        .ok_or(P7sError::OffsetNotFound("content signature"))?;
    let content_sig_len = content_sig_bytes.len();

    // ── SignerInfo signedAttrs (CAdES / CMS authenticated attributes) ─
    // DIIA p7s uses signedAttrs, so the signature covers SHA-256 of the
    // DER-encoded signedAttrs SET (with [0] IMPLICIT 0xA0 rewritten to
    // 0x31). Locate its byte range in the p7s.
    let signed_attrs = signer_info
        .signed_attrs
        .as_ref()
        .ok_or(P7sError::Cms("signerInfo has no signedAttrs (not a CAdES-BES doc)".into()))?;
    let signed_attrs_set_der = signed_attrs
        .to_der()
        .map_err(|e| P7sError::Cms(format!("signedAttrs encode: {e}")))?;
    // Rewrite 0x31 (SET) → 0xA0 ([0] IMPLICIT) to match the form in p7s
    let mut signed_attrs_implicit = signed_attrs_set_der.clone();
    if signed_attrs_implicit.is_empty() || signed_attrs_implicit[0] != 0x31 {
        return Err(P7sError::Cms("signedAttrs DER did not start with SET tag".into()));
    }
    signed_attrs_implicit[0] = 0xA0;
    let signed_attrs_start = find_subslice_unique(p7s, &signed_attrs_implicit)
        .ok_or(P7sError::OffsetNotFound("signedAttrs"))?;
    let signed_attrs_len = signed_attrs_implicit.len();

    // Locate the messageDigest attribute value (OCTET STRING content, 32 bytes for SHA-256).
    const OID_MESSAGE_DIGEST: ObjectIdentifier =
        ObjectIdentifier::new_unwrap("1.2.840.113549.1.9.4");
    let md_attr = signed_attrs
        .iter()
        .find(|a| a.oid == OID_MESSAGE_DIGEST)
        .ok_or(P7sError::Cms("messageDigest attribute not found in signedAttrs".into()))?;
    // Attribute value is a SET containing one Any wrapping an OCTET STRING.
    let md_value_any = md_attr
        .values
        .iter()
        .next()
        .ok_or(P7sError::Cms("messageDigest has no values".into()))?;
    let md_any_der = md_value_any
        .to_der()
        .map_err(|e| P7sError::Der(format!("messageDigest value encode: {e}")))?;
    // Strip OCTET STRING tag+length to get the 32-byte digest
    let md_bytes = strip_tag_and_length(&md_any_der)?;
    if md_bytes.len() != 32 {
        return Err(P7sError::Cms(format!(
            "messageDigest length {} != 32 (not SHA-256)",
            md_bytes.len()
        )));
    }
    // The 32-byte digest may appear twice (also inside signingCertificateV2).
    // Locate the unique messageDigest attribute DER, then offset to its OCTET STRING content.
    let md_attr_der = md_attr
        .to_der()
        .map_err(|e| P7sError::Cms(format!("messageDigest attr encode: {e}")))?;
    let md_attr_pos = find_subslice_unique(p7s, &md_attr_der)
        .ok_or(P7sError::OffsetNotFound("messageDigest attribute"))?;
    let message_digest_start = md_attr_pos + md_attr_der.len() - md_bytes.len();
    let message_digest_len = md_bytes.len();

    // messageDigest offset WITHIN signed_attrs (not absolute in p7s).
    // The 17-byte CMS messageDigest DER prefix sits at
    // `signed_attrs[md_offset..md_offset + 17]` and the 32-byte SHA-256
    // value at `signed_attrs[md_offset + 17..md_offset + 49]`. Mirror of
    // the in-circuit anchor in
    // vendor/longfellow-zk/lib/circuits/p7s/p7s_zk.cc's
    // build_hash_circuit (invariant 2c, Task 31). The host-side anchor
    // check below is the debuggability bound; the in-circuit anchor
    // assertion is the soundness bound (both use the same 17 bytes).
    // Gated by the `test-bypass-host-anchors` Cargo feature so
    // test-11b-style tests can construct a lying-offset witness and
    // prove that the circuit rejects it. Production builds never
    // enable the feature.
    const MD_PREFIX_LEN: usize = 17;
    let signed_attrs_md_offset = message_digest_start
        .checked_sub(signed_attrs_start)
        .and_then(|p| p.checked_sub(MD_PREFIX_LEN))
        .ok_or(P7sError::OffsetNotFound(
            "messageDigest within signed_attrs",
        ))?;
    #[cfg(not(feature = "test-bypass-host-anchors"))]
    {
        let md_prefix_actual =
            &p7s[signed_attrs_start + signed_attrs_md_offset..][..MD_PREFIX_LEN];
        if md_prefix_actual != CMS_MESSAGE_DIGEST_ATTR_PREFIX {
            return Err(P7sError::Cms(
                "CMS messageDigest DER prefix does not match template".into(),
            ));
        }
    }

    // ── JSON fields inside signed_content ─────────────────────────────
    let (json_pk_start_rel, json_pk_len) = locator::locate_hex_field(json_bytes, b"pk", 130)
        .ok_or(P7sError::JsonFieldMissing("pk"))?;
    let (json_nonce_start_rel, json_nonce_len) =
        locator::locate_hex_field(json_bytes, b"nonce", 64)
            .ok_or(P7sError::JsonFieldMissing("nonce"))?;
    let (json_context_start_rel, json_context_len) =
        locator::locate_string_field(json_bytes, b"context")
            .ok_or(P7sError::JsonFieldMissing("context"))?;
    let (json_declaration_start_rel, json_declaration_len) =
        locator::locate_string_field(json_bytes, b"declaration")
            .ok_or(P7sError::JsonFieldMissing("declaration"))?;
    let (json_timestamp_start_rel, json_timestamp_len) =
        locator::locate_integer_field(json_bytes, b"timestamp")
            .ok_or(P7sError::JsonFieldMissing("timestamp"))?;

    Ok(P7sOffsets {
        signed_content_start,
        signed_content_len,
        cert_start,
        cert_len,
        cert_tbs_start,
        cert_tbs_len,
        cert_tbs_spki_offset,
        cert_sig_start,
        cert_sig_len,
        subject_sn_start,
        subject_sn_len,
        subject_sn_offset_in_tbs,
        subject_dn_start_offset_in_tbs,
        user_signing_pk_start,
        content_sig_start,
        content_sig_len,
        signed_attrs_start,
        signed_attrs_len,
        signed_attrs_md_offset,
        message_digest_start,
        message_digest_len,
        json_pk_start: signed_content_start + json_pk_start_rel,
        json_pk_len,
        json_nonce_start: signed_content_start + json_nonce_start_rel,
        json_nonce_len,
        json_context_start: signed_content_start + json_context_start_rel,
        json_context_len,
        json_declaration_start: signed_content_start + json_declaration_start_rel,
        json_declaration_len,
        json_timestamp_start: signed_content_start + json_timestamp_start_rel,
        json_timestamp_len,
        trust_anchor_index,
    })
}

/// Find the first signer certificate that is a plain X.509 Certificate.
fn first_x509_cert(
    set: &cms::signed_data::CertificateSet,
) -> Result<Certificate, P7sError> {
    use cms::cert::CertificateChoices;
    for choice in set.0.iter() {
        if let CertificateChoices::Certificate(cert) = choice {
            return Ok(cert.clone());
        }
    }
    Err(P7sError::NoCerts)
}

/// Given DER of an Any that wraps an OCTET STRING, return the inner bytes.
/// Handles the `[0] EXPLICIT OCTET STRING` pattern used in eContent.
fn strip_any_octet_string(any_der: &[u8]) -> Result<&[u8], P7sError> {
    // An Any wrapping `[0] EXPLICIT OCTET STRING { bytes }`:
    //   A0 <len> 04 <len> <bytes>
    // Or bare OCTET STRING:
    //   04 <len> <bytes>
    let (mut rest, _) = read_tag_and_length(any_der)?;
    // If we see another OCTET STRING tag, strip it too
    if !rest.is_empty() && rest[0] == 0x04 {
        let (inner, _) = read_tag_and_length(rest)?;
        rest = inner;
    }
    Ok(rest)
}

/// Strip the outer ASN.1 tag and length, returning only the value bytes.
fn strip_tag_and_length(der: &[u8]) -> Result<&[u8], P7sError> {
    read_tag_and_length(der).map(|(rest, _tag)| rest)
}

/// Read an ASN.1 DER tag+length prefix. Returns (value, tag).
fn read_tag_and_length(der: &[u8]) -> Result<(&[u8], u8), P7sError> {
    if der.len() < 2 {
        return Err(P7sError::Der("truncated TLV".into()));
    }
    let tag = der[0];
    let len_byte = der[1];
    let (len, header_len) = if len_byte & 0x80 == 0 {
        (len_byte as usize, 2)
    } else {
        let n = (len_byte & 0x7f) as usize;
        if n == 0 || n > 4 || der.len() < 2 + n {
            return Err(P7sError::Der(format!("bad length byte: {len_byte}")));
        }
        let mut v = 0usize;
        for i in 0..n {
            v = (v << 8) | der[2 + i] as usize;
        }
        (v, 2 + n)
    };
    if der.len() < header_len + len {
        return Err(P7sError::Der("truncated value".into()));
    }
    Ok((&der[header_len..header_len + len], tag))
}

/// Find `needle` in `haystack`. Returns `None` if absent or non-unique.
fn find_subslice_unique(haystack: &[u8], needle: &[u8]) -> Option<usize> {
    if needle.is_empty() {
        return None;
    }
    let mut first = None;
    let mut i = 0;
    while i + needle.len() <= haystack.len() {
        if &haystack[i..i + needle.len()] == needle {
            if first.is_some() {
                return None; // non-unique — ambiguous offset
            }
            first = Some(i);
            i += needle.len();
        } else {
            i += 1;
        }
    }
    first
}

/// `true` iff `needle` appears as a contiguous sub-slice of `haystack`
/// at least once. Unlike `find_subslice_unique`, multiple matches are
/// fine — trust-anchor probe markers just need presence, not position.
fn contains_subslice(haystack: &[u8], needle: &[u8]) -> bool {
    if needle.is_empty() || needle.len() > haystack.len() {
        return false;
    }
    haystack.windows(needle.len()).any(|w| w == needle)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Verify that no `TRUST_ANCHOR_PROBES` marker is a substring of
    /// another. The selection uses `find_map` (first-match) over the
    /// probe list, so if marker A is a prefix/suffix/substring of marker
    /// B, a cert issued by B's QTSP would incorrectly resolve to A's
    /// trust-anchor index (whichever marker appears first in the list).
    ///
    /// This test fails LOUDLY when a new probe is added that would
    /// create an ambiguity — e.g. a short marker `TEST-00` that matches
    /// inside the longer `TEST-00000000-01`. Reviewer-2 audit nit N1
    /// from Task #42 (P2b-36n).
    ///
    /// For the current N=1 table this is trivially satisfied, but the
    /// check is future-proof: it catches the bug for N≥2 before any
    /// fixture exercises the issue.
    #[test]
    fn trust_anchor_probes_are_unique() {
        let probes = TRUST_ANCHOR_PROBES;
        for (i, (a, _idx_a, name_a)) in probes.iter().enumerate() {
            for (j, (b, _idx_b, name_b)) in probes.iter().enumerate() {
                if i == j {
                    continue;
                }
                // a must not be a substring of b (and vice versa — the
                // j>i case catches that on the symmetric iteration).
                assert!(
                    !contains_subslice(b, a),
                    "TRUST_ANCHOR_PROBES collision: marker #{i} ({name_a:?} = {:?}) \
                     is a substring of marker #{j} ({name_b:?} = {:?}); \
                     find_map would match #{i} on #{j}'s certs, assigning \
                     the wrong trust-anchor index",
                    std::str::from_utf8(a).unwrap_or("<non-utf8>"),
                    std::str::from_utf8(b).unwrap_or("<non-utf8>"),
                );
            }
        }
    }
}
