#!/bin/bash
# Download large circuit artifacts not stored in git.
# URLs are read from artifact-urls.json (generated by scripts/upload-artifacts.mjs).
# Run from the circuits/ directory.

set -euo pipefail
cd "$(dirname "$0")"

if [ ! -f "artifact-urls.json" ]; then
  echo "ERROR: artifact-urls.json not found. Run 'node scripts/upload-artifacts.mjs' first."
  exit 1
fi

ECDSA_ZKEY_URL=$(jq -r '.ecdsa_verify_zkey' artifact-urls.json)
ECDSA_CVM_URL=$(jq -r '.ecdsa_verify_cvm' artifact-urls.json)
PTAU21_URL=$(jq -r '.ptau21' artifact-urls.json)
PTAU22_URL=$(jq -r '.ptau22' artifact-urls.json)

mkdir -p build/ecdsa_verify build/ecdsa_verify_cvm

if [ ! -f "build/ecdsa_verify/ecdsa_verify.zkey" ]; then
  echo "Downloading ecdsa_verify.zkey (1.2 GB)..."
  curl -L -o build/ecdsa_verify/ecdsa_verify.zkey "$ECDSA_ZKEY_URL"
else
  echo "ecdsa_verify.zkey already exists, skipping."
fi

if [ ! -f "build/ecdsa_verify_cvm/ecdsa_verify.cvm" ]; then
  echo "Downloading ecdsa_verify.cvm (58 MB)..."
  curl -L -o build/ecdsa_verify_cvm/ecdsa_verify.cvm "$ECDSA_CVM_URL"
else
  echo "ecdsa_verify.cvm already exists, skipping."
fi

if [ ! -f "pot21.ptau" ]; then
  echo "Downloading pot21.ptau (2.4 GB)..."
  curl -L -o pot21.ptau "$PTAU21_URL"
else
  echo "pot21.ptau already exists, skipping."
fi

if [ ! -f "pot22.ptau" ]; then
  echo "Downloading pot22.ptau (4.6 GB)..."
  curl -L -o pot22.ptau "$PTAU22_URL"
else
  echo "pot22.ptau already exists, skipping."
fi

echo "All artifacts ready."
